language: node_js
node_js:
- 12

################
before_install:
- node --version
- npm --version
- npm install -g jest
- npm install
- npm install -g coveralls

################
script:
- npm run testrel
