# https://circleci.com/developer/orbs/orb/circleci/node
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  phdcc_papers_api_coverage:
    jobs:
      - test_coverage
jobs:
  test_coverage:
    executor: node/default
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
#          lts: true
          node-version: '12.20'
#          cache-path: ~/project/node_modules
#          override-ci-command: npm install
      - run: npm install coveralls
      - run: npm install jest
      - run: npm -v
      - run: node -v
      - run: mkdir testtmpdir
      - run: npm run testci -- --runInBand
      - run: node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info # .coveralls.yml must contain circleci
