version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  phdcc_papers_api_coverage:
    jobs:
      - test_coverage
jobs:
  test_coverage:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm install jest
      - run: npm install coveralls
      - run: mkdir testtmpdir
      - run: npm run testci
      - run: node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info # .coveralls.yml must contain circleci
